// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtXl73n-PJlQp50NgCXy5Mi5l61tt03q4',
    appId: '1:1078178068128:web:b1bb1e312a8b7fd3a1fbc5',
    messagingSenderId: '1078178068128',
    projectId: 'mensapp-c2755',
    authDomain: 'mensapp-c2755.firebaseapp.com',
    storageBucket: 'mensapp-c2755.firebasestorage.app',
    measurementId: 'G-1ZGJCQ6TL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIGa6SsWtPh2iN4DTGKx2Stwh8l5XHhtY',
    appId: '1:1078178068128:android:9c4fe262c9ca0405a1fbc5',
    messagingSenderId: '1078178068128',
    projectId: 'mensapp-c2755',
    storageBucket: 'mensapp-c2755.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi1zdtIGh0COVJ8DVDjF7PQDiBYQo4Puw',
    appId: '1:1078178068128:ios:2966b1e9d3a9ab04a1fbc5',
    messagingSenderId: '1078178068128',
    projectId: 'mensapp-c2755',
    storageBucket: 'mensapp-c2755.firebasestorage.app',
    iosBundleId: 'com.example.mensApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi1zdtIGh0COVJ8DVDjF7PQDiBYQo4Puw',
    appId: '1:1078178068128:ios:2966b1e9d3a9ab04a1fbc5',
    messagingSenderId: '1078178068128',
    projectId: 'mensapp-c2755',
    storageBucket: 'mensapp-c2755.firebasestorage.app',
    iosBundleId: 'com.example.mensApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtXl73n-PJlQp50NgCXy5Mi5l61tt03q4',
    appId: '1:1078178068128:web:5871413484aba9e6a1fbc5',
    messagingSenderId: '1078178068128',
    projectId: 'mensapp-c2755',
    authDomain: 'mensapp-c2755.firebaseapp.com',
    storageBucket: 'mensapp-c2755.firebasestorage.app',
    measurementId: 'G-QZG29L7T8F',
  );
}
